# -*- coding: utf-8 -*-
"""crisp_dm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14Uii8ZQuaZz07sf_Z39IzTDfMam_xw81
"""

!pip install -q pandas numpy scikit-learn matplotlib seaborn sentence-transformers transformers accelerate torch

import pandas as pd
import numpy as np

# 1. Load Data Dictionary
print("--- DATA DICTIONARY DEFINITIONS ---")
dict_df = pd.read_excel('Leads Data Dictionary.xlsx')
pd.set_option('display.max_colwidth', None)
display(dict_df)

# 2. Load Raw Dataset
df = pd.read_csv('Lead Scoring.csv')
print(f"\nDataset Dimensions: {df.shape[0]} rows, {df.shape[1]} columns\n")

# 3. Check Target Conversion Rate
print("--- TARGET VARIABLE DISTRIBUTION ('Converted') ---")
print(df['Converted'].value_counts(normalize=True) * 100)

# 4. Detect Unselected Dropdown Placeholders ('Select')
select_counts = (df == 'Select').sum()
print("\n--- COLUMNS CONTAINING 'Select' PLACEHOLDERS ---")
print(select_counts[select_counts > 0])

# Create a copy for cleaning
df_clean = df.copy()

# Replace 'Select' placeholders with NaN
df_clean = df_clean.replace('Select', np.nan)

# Key categorical and numerical columns for profiling
cat_cols = [
    'Lead Source', 'Last Activity', 'Specialization',
    'What is your current occupation',
    'What matters most to you in choosing a course',
    'City'
]
num_cols = ['TotalVisits', 'Total Time Spent on Website', 'Page Views Per Visit'] # Corrected column name

# Fill missing categorical values with 'Unknown'
for col in cat_cols:
    df_clean[col] = df_clean[col].fillna('Unknown')

# Fill missing numerical values with 0
for col in num_cols:
    df_clean[col] = df_clean[col].fillna(0)

# Build narrative string for Hugging Face vector embeddings
def create_context_string(row):
    return (
        f"Occupation: {row['What is your current occupation']} | "
        f"Specialization: {row['Specialization']} | "
        f"Primary Goal: {row['What matters most to you in choosing a course']} | "
        f"Lead Source: {row['Lead Source']} | "
        f"Last Activity: {row['Last Activity']} | "
        f"City: {row['City']} | "
        f"Time Spent on Site: {int(row['Total Time Spent on Website'])} seconds | "
        f"Total Visits: {int(row['TotalVisits'])}" # Corrected column name
    )

df_clean['Lead_Context_String'] = df_clean.apply(create_context_string, axis=1)

print("Data Cleaning Complete!")
print("\nSample Generated Context String:")
print(df_clean['Lead_Context_String'].iloc[0])

import pandas as pd
import numpy as np

# 1. Deduplicate based on Prospect ID
df_clean = df.drop_duplicates(subset=['Prospect ID']).copy()

# 2. Hard Filter: Remove leads who opted out of email outreach
df_clean = df_clean[df_clean['Do Not Email'] != 'Yes']

# 3. Replace 'Select' placeholders with NaN
df_clean = df_clean.replace('Select', np.nan)

# 4. Standardize Categorical Channels
df_clean['Lead Source'] = df_clean['Lead Source'].replace({
    'google': 'Google',
    'facebook': 'Facebook',
    'blog': 'Organic Search'
})

# Group rare Lead Sources (appearing less than 10 times) into 'Other'
source_counts = df_clean['Lead Source'].value_counts()
rare_sources = source_counts[source_counts < 10].index
df_clean['Lead Source'] = df_clean['Lead Source'].replace(rare_sources, 'Other')

# 5. Fill missing values
cat_cols = [
    'Lead Source', 'Last Activity', 'Specialization',
    'What is your current occupation',
    'What matters most to you in choosing a course',
    'City'
]
for col in cat_cols:
    df_clean[col] = df_clean[col].fillna('Unknown')

df_clean['TotalVisits'] = df_clean['TotalVisits'].fillna(0)
df_clean['Total Time Spent on Website'] = df_clean['Total Time Spent on Website'].fillna(0)

# Cap extreme outliers in TotalVisits at the 99th percentile
cap_visits = df_clean['TotalVisits'].quantile(0.99)
df_clean['TotalVisits'] = np.where(df_clean['TotalVisits'] > cap_visits, cap_visits, df_clean['TotalVisits'])

# 6. Feature Engineering: Convert raw time spent (seconds) to qualitative engagement bands
def convert_time_to_band(seconds):
    if seconds == 0:
        return "No Site Engagement"
    elif seconds < 180:
        return f"Low Engagement ({int(seconds // 60)} mins)"
    elif seconds < 600:
        return f"Moderate Engagement ({int(seconds // 60)} mins)"
    else:
        return f"High Engagement ({int(seconds // 60)} mins)"

df_clean['Engagement_Band'] = df_clean['Total Time Spent on Website'].apply(convert_time_to_band)

# ----------------------------------------------------
# MODIFICATION 1: DOMAIN DENSITY & CONTEXT STRING ENRICHMENT
# ----------------------------------------------------
# 1. Compute historical conversion counts per domain
# ====================================================
# MODIFICATION 1: DOMAIN TIERING & NARRATIVE STRING
# ====================================================
converted_df_all = df_clean[df_clean['Converted'] == 1]
domain_stats = converted_df_all.groupby('Specialization').size().to_dict()

def get_domain_tier(specialization):
    conversions = domain_stats.get(specialization, 0)
    if conversions > 20:
        return f"High-Converting Sector ({conversions} past buyers)"
    elif conversions > 5:
        return f"Active Sector ({conversions} past buyers)"
    else:
        return f"Emerging Sector ({conversions} past buyers)"

df_clean['Domain_Tier'] = df_clean['Specialization'].apply(get_domain_tier)

def build_domain_context_string(row):
    return (
        f"Domain Sector: {row['Specialization']} [{row['Domain_Tier']}] | "
        f"Role: {row['What is your current occupation']} | "
        f"Goal: {row['What matters most to you in choosing a course']} | "
        f"Channel: {row['Lead Source']} | "
        f"City: {row['City']} | "
        f"Engagement: {row['Engagement_Band']}"
    )

df_clean['Lead_Context_String'] = df_clean.apply(build_domain_context_string, axis=1)

# Sample 100 benchmark buyers & 50 target prospects
converted_df = df_clean[df_clean['Converted'] == 1].sample(n=100, random_state=42).copy()
unscored_df = df_clean[df_clean['Converted'] == 0].sample(n=50, random_state=42).copy()

from sentence_transformers import SentenceTransformer
from sklearn.metrics.pairwise import cosine_similarity
import numpy as np

# 1. Load lightweight Hugging Face embedding model
print("Loading SentenceTransformer model ('all-MiniLM-L6-v2')...")
# ====================================================
# MODIFICATION 2: EMBEDDINGS & DOMAIN AFFINITY BOOST
# ====================================================
embedder = SentenceTransformer('all-MiniLM-L6-v2')

converted_vectors = embedder.encode(converted_df['Lead_Context_String'].tolist(), show_progress_bar=True)
unscored_vectors = embedder.encode(unscored_df['Lead_Context_String'].tolist(), show_progress_bar=True)

sim_matrix = cosine_similarity(unscored_vectors, converted_vectors)
lead_scores = []
similar_customers_formatted = []
for i, (target_idx, target_row) in enumerate(unscored_df.iterrows()):
    target_domain = target_row['Specialization']
    target_sims = sim_matrix[i].copy()
    # Apply 1.20x boost for matching domain
    for j, (conv_idx, conv_row) in enumerate(converted_df.iterrows()):
        if conv_row['Specialization'] == target_domain and target_domain != 'Unknown':
            target_sims[j] = min(1.0, target_sims[j] * 1.20)
    top_2_indices = np.argsort(target_sims)[-2:][::-1]
    best_score = round(float(target_sims[top_2_indices[0]]) * 100, 2)
    lead_scores.append(best_score)
    matches_text = []
    for rank, match_idx in enumerate(top_2_indices, 1):
        match_row = converted_df.iloc[match_idx]
        match_sim = round(float(target_sims[match_idx]) * 100, 1)
        matches_text.append(
            f"{rank}. {match_row['Specialization']} ({match_row['What is your current occupation']}) - "
            f"Converted via {match_row['Lead Source']} with {match_row['Engagement_Band']} (Match: {match_sim}%)."
        )
    similar_customers_formatted.append("\n".join(matches_text))

from google.colab import files
# Build DataFrame with the exact 8 columns requested by your partner
# ====================================================
# MODIFICATION 3: EXPORT 50 PROSPECTS TO CSV
# ====================================================
scored_leads_df = pd.DataFrame({
    'lead_id': "LEAD_" + unscored_df['Lead Number'].astype(str),
    'lead_name': "Prospect " + unscored_df['Lead Number'].astype(str),
    'lead_title': unscored_df['What is your current occupation'],
    'company_name': "Unknown",
    'industry': unscored_df['Specialization'],
    'company_size': 100,
    'lead_score': lead_scores,
    'similar_customers': similar_customers_formatted
}).sort_values(by='lead_score', ascending=False)
output_filename = 'scored_leads.csv'
scored_leads_df.to_csv(output_filename, index=False)
files.download(output_filename)
print(f"SUCCESS: Exported {len(scored_leads_df)} scored leads to '{output_filename}'!")
display(scored_leads_df.head(5))